login: &login
  adapter: postgresql
  encoding: unicode
  username: jadams
  pool: 5

development: &development
  database: isotope_contacts_demo_development
  <<: *login

test: &test
  database: isotope_contacts_demo_test
  <<: *login
cucumber: &cucumber
  database: isotope_contacts_demo_cucumber
  <<: *login

production: &production
  database: isotope_contacts_demo_production
  <<: *login
